#!/bin/bash
# Media auto-import installer.
# Run once per Mac. Generates per-user LaunchAgents with no hardcoded paths.
#
# Usage:
#   ./install.sh           interactive (prompts to open System Settings)
#   ./install.sh --quiet   non-interactive (used by update.sh)
set -e

QUIET=0
[[ "${1:-}" == "--quiet" ]] && QUIET=1

# Resolve install location from this script's own path — no hardcoded user paths.
INSTALL_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_PATH="$INSTALL_DIR/import-media.sh"
UPDATE_PATH="$INSTALL_DIR/update.sh"
NOTIFY_PATH="$INSTALL_DIR/notify-uploads.sh"

# Per-user destination paths derived from $HOME.
LA_DIR="$HOME/Library/LaunchAgents"
LOG_DIR="$HOME/Library/Logs"
MOVIES_DIR="$HOME/Movies"
APPS_DIR="$HOME/Applications"
APP_BUNDLE="$APPS_DIR/MediaImport.app"
APP_EXEC="$APP_BUNDLE/Contents/MacOS/MediaImport"

IMPORT_PLIST="$LA_DIR/com.user.importmedia.plist"
UPDATE_PLIST="$LA_DIR/com.user.importmedia.update.plist"
NOTIFY_PLIST="$LA_DIR/com.user.importmedia.notify.plist"

mkdir -p "$LA_DIR" "$LOG_DIR" "$MOVIES_DIR" "$APP_BUNDLE/Contents/MacOS"
chmod +x "$INSTALL_DIR"/*.sh

# Per-user config (lives outside the repo, survives git pull updates).
CONFIG_DIR="$HOME/.config/import-media"
CONFIG_FILE="$CONFIG_DIR/config.sh"
DEST_FILE="$CONFIG_DIR/dest-base.txt"
mkdir -p "$CONFIG_DIR"
if [[ ! -f "$CONFIG_FILE" ]]; then
  # Default = Soma team customization.
  cat > "$CONFIG_FILE" <<'EOF'
# Generated by install.sh (Soma team defaults).
# Edit via GUI: ~/.import-media/settings.sh  (or double-click 取り込み設定 on Desktop)
RETENTION_DAYS=30
FILE_FILTER="mp4_only"
DELETE_FROM_CARD="false"
VERIFY_MODE="size"
EOF
  echo "✏️  Personal config (Soma team defaults) created at: $CONFIG_FILE"
fi

# ---------- Desktop shortcut for settings GUI ----------
# A tiny .app bundle so double-click opens the settings UI with no Terminal window.
SETTINGS_APP="$HOME/Desktop/取り込み設定.app"
mkdir -p "$SETTINGS_APP/Contents/MacOS"
cat > "$SETTINGS_APP/Contents/Info.plist" <<'PLIST_EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>Settings</string>
    <key>CFBundleIdentifier</key>
    <string>com.user.importmedia.settings</string>
    <key>CFBundleName</key>
    <string>取り込み設定</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>LSUIElement</key>
    <true/>
</dict>
</plist>
PLIST_EOF
cat > "$SETTINGS_APP/Contents/MacOS/Settings" <<EOF
#!/bin/bash
exec "$INSTALL_DIR/settings.sh"
EOF
chmod +x "$SETTINGS_APP/Contents/MacOS/Settings"
touch "$SETTINGS_APP"

# On first install (no destination chosen yet), pop a folder picker so the user
# can pick where videos should go. Skipped in --quiet mode (auto-update reruns).
if [[ $QUIET -eq 0 ]] && [[ ! -f "$DEST_FILE" ]]; then
  /bin/bash "$INSTALL_DIR/set-destination.sh" || true
fi

# ---------- Generate wrapper .app bundle ----------
# macOS won't let you grant Full Disk Access to /bin/bash directly on recent versions,
# so we wrap our script inside a .app bundle that can be FDA-granted via Finder drag.
cat > "$APP_BUNDLE/Contents/Info.plist" <<'PLIST_EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>MediaImport</string>
    <key>CFBundleIdentifier</key>
    <string>com.user.mediaimport</string>
    <key>CFBundleName</key>
    <string>MediaImport</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>LSUIElement</key>
    <true/>
</dict>
</plist>
PLIST_EOF

cat > "$APP_EXEC" <<EOF
#!/bin/bash
exec "$SCRIPT_PATH" "\$@"
EOF
chmod +x "$APP_EXEC"
touch "$APP_BUNDLE"

# ---------- Generate import LaunchAgent ----------
cat > "$IMPORT_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.user.importmedia</string>
    <key>ProgramArguments</key>
    <array>
        <string>$APP_EXEC</string>
    </array>
    <key>WatchPaths</key>
    <array>
        <string>/Volumes</string>
        <string>$HOME/Downloads</string>
    </array>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/import-media.out.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/import-media.err.log</string>
</dict>
</plist>
EOF

# ---------- Generate auto-update LaunchAgent (daily 4 AM) ----------
cat > "$UPDATE_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.user.importmedia.update</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$UPDATE_PATH</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>4</integer>
        <key>Minute</key>
        <integer>0</integer>
    </dict>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/import-media-update.out.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/import-media-update.err.log</string>
</dict>
</plist>
EOF

# ---------- Generate upload-notify LaunchAgent (every 2 min) ----------
# Sends the deferred LINE notification once a session's files finish uploading
# to the Drive cloud. Harmless on Macs without ~/bin/notify-line.sh (no-op).
cat > "$NOTIFY_PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.user.importmedia.notify</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>$NOTIFY_PATH</string>
    </array>
    <key>StartInterval</key>
    <integer>120</integer>
    <key>StandardOutPath</key>
    <string>$LOG_DIR/import-media-notify.out.log</string>
    <key>StandardErrorPath</key>
    <string>$LOG_DIR/import-media-notify.err.log</string>
</dict>
</plist>
EOF

# ---------- (Re-)load LaunchAgents ----------
launchctl unload "$IMPORT_PLIST" 2>/dev/null || true
launchctl unload "$UPDATE_PLIST" 2>/dev/null || true
launchctl unload "$NOTIFY_PLIST" 2>/dev/null || true
launchctl load -w "$IMPORT_PLIST"
launchctl load -w "$UPDATE_PLIST"
launchctl load -w "$NOTIFY_PLIST"

if [[ $QUIET -eq 1 ]]; then
  exit 0
fi

cat <<EOF

==========================================
✅ インストール完了
==========================================
スクリプト場所  : $SCRIPT_PATH
ラッパー .app   : $APP_BUNDLE
保存先          : $MOVIES_DIR/<ソース>/<年>/<日付>/<機種>/
ログ            : $LOG_DIR/import-media.log
自動アップデート : 毎日 04:00 に git pull
==========================================

次の手順（これをやらないと動きません）:
  1. Finder で ~/Applications を開く（Cmd+Shift+G で ~/Applications）
  2. システム設定 → プライバシーとセキュリティ → フルディスクアクセス
  3. Finder の MediaImport アプリを、FDA リストに **ドラッグ＆ドロップ**
  4. 追加された MediaImport のトグルを ON にする
  5. SDカードを差すか AirDrop で動画を受信 → 自動取り込み開始

EOF

if [[ -t 0 ]]; then
  read -r -p "今すぐシステム設定を開きますか？ (y/N) " yn
  if [[ "$yn" =~ ^[Yy] ]]; then
    open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles"
  fi
fi
