#!/usr/bin/env bash
# Interactive GUI settings for import-media.
# Launched by double-clicking 取り込み設定.app on the Desktop, or via terminal.
set -uo pipefail

CONFIG_DIR="$HOME/.config/import-media"
CONFIG_FILE="$CONFIG_DIR/config.sh"
DEST_FILE="$CONFIG_DIR/dest-base.txt"
mkdir -p "$CONFIG_DIR"

# Load current values (defaults if missing).
[[ -f "$CONFIG_FILE" ]] && source "$CONFIG_FILE" 2>/dev/null || true
CURRENT_DEST="$([[ -f "$DEST_FILE" ]] && /usr/bin/head -1 "$DEST_FILE" || echo "$HOME/Movies")"
CURRENT_RETENTION="${RETENTION_DAYS:-30}"
CURRENT_FILTER="${FILE_FILTER:-mp4_only}"
CURRENT_DELETE="${DELETE_FROM_CARD:-false}"
CURRENT_VERIFY="${VERIFY_MODE:-size}"
CURRENT_AUTO="${AUTO_IMPORT:-false}"

# Soma team defaults — applied via "リセット" menu choice.
soma_defaults() {
  CURRENT_RETENTION=30
  CURRENT_FILTER="mp4_only"
  CURRENT_DELETE="false"
  CURRENT_VERIFY="size"
  CURRENT_AUTO="false"
}

filter_label() { [[ "$1" == "mp4_only" ]] && echo "MP4のみ" || echo "すべて"; }
delete_label() { [[ "$1" == "true" ]] && echo "削除する" || echo "残す"; }
auto_label()   { [[ "$1" == "true" ]] && echo "ON（確認なしで全部取り込み）" || echo "OFF（確認ダイアログあり）"; }

save_config() {
  cat > "$CONFIG_FILE" <<EOF
# Generated by settings.sh. Edit via: ~/.import-media/settings.sh
# (or with Terminal as a fallback.)
RETENTION_DAYS=$CURRENT_RETENTION
FILE_FILTER="$CURRENT_FILTER"
DELETE_FROM_CARD="$CURRENT_DELETE"
VERIFY_MODE="$CURRENT_VERIFY"
AUTO_IMPORT="$CURRENT_AUTO"
EOF
  [[ -n "$CURRENT_DEST" ]] && printf '%s\n' "$CURRENT_DEST" > "$DEST_FILE"
}

# Main menu loop.
while true; do
  fl=$(filter_label "$CURRENT_FILTER")
  dl=$(delete_label "$CURRENT_DELETE")
  al=$(auto_label "$CURRENT_AUTO")
  dest_short="${CURRENT_DEST/#$HOME/~}"

  chosen=$(/usr/bin/osascript <<APPLESCRIPT 2>/dev/null
set theList to {¬
  "1. 保存先 — $dest_short", ¬
  "2. 取り込むファイル種類 — $fl", ¬
  "3. 自動削除期間 — ${CURRENT_RETENTION}日", ¬
  "4. SDカード側ファイル — $dl", ¬
  "5. コピー検証モード — $CURRENT_VERIFY", ¬
  "6. 自動取り込み（ハブ用） — $al", ¬
  "7. 無視するメディアを管理", ¬
  "8. 相馬チームのデフォルトに戻す", ¬
  "9. 保存して閉じる"¬
}
set userChoice to (choose from list theList with prompt "設定したい項目を選んでください" with title "取り込みシステム設定" OK button name "編集" cancel button name "閉じる")
if userChoice is false then return ""
return item 1 of userChoice as string
APPLESCRIPT
)
  [[ -z "$chosen" ]] && { save_config; break; }

  case "$chosen" in
    "1. "*)
      new_dest=$(/usr/bin/osascript -e 'POSIX path of (choose folder with prompt "保存先フォルダを選んでください")' 2>/dev/null || true)
      [[ -n "$new_dest" ]] && CURRENT_DEST="${new_dest%/}"
      ;;
    "2. "*)
      pick=$(/usr/bin/osascript <<A 2>/dev/null
set userChoice to (choose from list {"MP4のみ (推奨：LRV・THM・JPG等を除外)", "すべて (LRV・THM・JPG・RAW なども取り込む)"} with prompt "取り込むファイル種類" with title "ファイル種類")
if userChoice is false then return ""
return item 1 of userChoice as string
A
)
      case "$pick" in
        MP4*) CURRENT_FILTER="mp4_only" ;;
        すべて*) CURRENT_FILTER="all" ;;
      esac
      ;;
    "3. "*)
      ans=$(/usr/bin/osascript -e "text returned of (display dialog \"自動削除する日数を入力（0で無効）\" default answer \"$CURRENT_RETENTION\" with title \"自動削除期間\")" 2>/dev/null || true)
      [[ "$ans" =~ ^[0-9]+$ ]] && CURRENT_RETENTION="$ans"
      ;;
    "4. "*)
      pick=$(/usr/bin/osascript <<A 2>/dev/null
set userChoice to (display dialog "SDカード側のファイル：取り込み完了後どうしますか？" buttons {"残す (推奨)", "削除する"} default button "残す (推奨)" with title "SDカード処理")
return button returned of userChoice
A
)
      [[ "$pick" == "削除する" ]] && CURRENT_DELETE="true" || CURRENT_DELETE="false"
      ;;
    "5. "*)
      pick=$(/usr/bin/osascript <<A 2>/dev/null
set userChoice to (choose from list {"size (推奨・速い)", "hash (バイト単位完全一致・遅い)", "none (rsyncの判定のみ)"} with prompt "コピー検証モード" with title "検証モード")
if userChoice is false then return ""
return item 1 of userChoice as string
A
)
      case "$pick" in size*) CURRENT_VERIFY="size" ;; hash*) CURRENT_VERIFY="hash" ;; none*) CURRENT_VERIFY="none" ;; esac
      ;;
    "6. "*)
      pick=$(/usr/bin/osascript <<A 2>/dev/null
set userChoice to (choose from list {"ON（確認なしで認識した全カードを自動取り込み・ハブ向け）", "OFF（カードごとに確認ダイアログを出す）"} with prompt "自動取り込みモード" with title "自動取り込み（ハブ用）")
if userChoice is false then return ""
return item 1 of userChoice as string
A
)
      case "$pick" in ON*) CURRENT_AUTO="true" ;; OFF*) CURRENT_AUTO="false" ;; esac
      ;;
    "7. "*)
      pick=$(/usr/bin/osascript <<A 2>/dev/null
set userChoice to (choose from list {"無視するメディアを追加", "無視リストから削除"} with prompt "無視リスト管理" with title "メディア管理")
if userChoice is false then return ""
return item 1 of userChoice as string
A
)
      case "$pick" in
        無視するメディアを追加) /bin/bash "$(/usr/bin/dirname "$0")/ignore-volume.sh" || true ;;
        無視リストから削除) /bin/bash "$(/usr/bin/dirname "$0")/unignore-volume.sh" || true ;;
      esac
      ;;
    "8. "*)
      soma_defaults
      /usr/bin/osascript -e 'display notification "相馬チームのデフォルトに戻しました" with title "取り込みシステム" sound name "Glass"' >/dev/null 2>&1 || true
      ;;
    "9. "*)
      save_config
      /usr/bin/osascript -e 'display notification "設定を保存しました" with title "取り込みシステム" sound name "Glass"' >/dev/null 2>&1 || true
      break
      ;;
  esac
done
